  AddScoreDb[m
  Attack_Preventer[m
  Command_Injection[m
  DB_Warrper_Prefrences[m
  DataBaseWAF[m
  DbWrapperUpdate[m
  Develop[m
  File_Attacks[m
  First_Sprint[m
  PraserAndClassifier[m
  Prefrences_with_routing[m
  Routing[m
  SQLI[m
  Second_Sprint[m
  SlowLoris_connecting[m
  SqlInjection[m
* [32mThird_Sprint[m
  clickJacking[m
  connectRoutingWithDB[m
  ddosAttack[m
  logger[m
  logger_with_routing[m
  orgenizeFiles[m
  slow_loris[m
